const mongoose = require('mongoose');
const { models } = require('./server/models');

async function fixIndices() {
    try {
        await mongoose.connect('mongodb://localhost:27017/erpnext');
        console.log('Connected to MongoDB');

        const Student = mongoose.model('Student');

        // 1. Get current indexes
        const currentIndexes = await Student.collection.getIndexes();
        console.log('Current Indexes:', Object.keys(currentIndexes));

        // 2. Drop problematic indexes if they exist without partialFilter
        // The index names are usually generated by mongoose, but they follow a pattern
        for (const name of Object.keys(currentIndexes)) {
            if (name.includes('studentId') || name.includes('username') || name.includes('email')) {
                console.log(`Dropping index: ${name}`);
                await Student.collection.dropIndex(name);
            }
        }

        // 3. Inspect Data for duplicates or bad strings
        const students = await Student.find({});
        console.log(`Inspecting ${students.length} students...`);

        const badValues = ["", "undefined", "null", "undefined ", "null "];
        let cleaned = 0;

        for (const s of students) {
            let update = {};
            if (badValues.includes(String(s.studentId).trim())) update.studentId = 1;
            if (badValues.includes(String(s.username).trim())) update.username = 1;
            if (badValues.includes(String(s.email).trim())) update.email = 1;

            if (Object.keys(update).length > 0) {
                console.log(`Cleaning student: ${s.studentName} (${s._id}) - Fields: ${Object.keys(update)}`);
                await Student.updateOne({ _id: s._id }, { $unset: update });
                cleaned++;
            }
        }
        console.log(`Cleaned ${cleaned} records.`);

        // 4. Force Rebuild Indexes (using the ones defined in the Schema)
        console.log('Synchronizing indexes...');
        await Student.syncIndexes();

        const afterIndexes = await Student.collection.getIndexes();
        console.log('Final Indexes:', JSON.stringify(afterIndexes, null, 2));

        process.exit(0);
    } catch (e) {
        console.error('ERROR:', e);
        process.exit(1);
    }
}

fixIndices();
